# Generated by Django 3.0.2 on 2020-04-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arogyasetu', '0003_auto_20200423_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
